import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")

MODE = os.getenv("MODE", "PAPER")
PAPER_SEED_USDT = float(os.getenv("PAPER_SEED_USDT", "1000"))

KST_TIMEZONE = "Asia/Seoul"

DEFAULT_LEVERAGE = 4
DEFAULT_ENTRY_1_PCT = 0.02
DEFAULT_ENTRY_2_PCT = 0.01
DEFAULT_ENTRY_3_PCT = 0.01
DEFAULT_PUMP_THRESHOLD_PCT = 3.0
DEFAULT_ADD_ENTRY_PRICE_MOVE_PCT = 5.0
DEFAULT_TAKE_PROFIT_LEVERAGED_PCT = 12.0
DEFAULT_STOP_LOSS_LEVERAGED_PCT = -30.0
