import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")

MODE = os.getenv("MODE", "PAPER")
PAPER_SEED_USDT = float(os.getenv("PAPER_SEED_USDT", "1000"))

KST_TIMEZONE = "Asia/Seoul"

DEFAULT_LEVERAGE = 4
DEFAULT_ENTRY_1_PCT = 0.02
DEFAULT_ENTRY_2_PCT = 0.01
DEFAULT_ENTRY_3_PCT = 0.01
DEFAULT_PUMP_THRESHOLD_PCT = 3.0

# 추가진입: 숏 기준 가격이 직전 진입가 대비 +5% 올라가면 다음 차수.
# 레버리지 4배 기준 약 -20% 손실 구간.
DEFAULT_ADD_ENTRY_PRICE_MOVE_PCT = 5.0

# 익절/손절: 레버리지 기준
DEFAULT_TAKE_PROFIT_LEVERAGED_PCT = 12.0
DEFAULT_STOP_LOSS_LEVERAGED_PCT = -30.0

BOT_VERSION = "FINAL v4.5.5 ADMIN-MONITOR"

# v4.3 실전 주문 테스트 기본값
REAL_TEST_SYMBOL = "DOGE-USDT"
REAL_TEST_MARGIN_USDT = 1.0

REAL_FIXED_LEVERAGE = 4

# v4.4: 09:15 전략 자동 실전 주문 활성화
LIVE_STRATEGY_ENABLED = True

LIVE_DAILY_MAX_ENTRIES = 1

# 관리자 승인용 chat_id. 비워두면 TELEGRAM_CHAT_ID를 관리자 ID로 사용.
ADMIN_CHAT_ID = os.getenv("ADMIN_CHAT_ID", TELEGRAM_CHAT_ID)
